<a href="https://colab.research.google.com/github/1zuu/Machine-Learning-With-Graphs/blob/main/1_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Dependency Installation**

In [1]:
import torch

def format_pytorch_version(version):
  return version.split('+')[0]

TORCH_version = torch.__version__
TORCH = format_pytorch_version(TORCH_version)

def format_cuda_version(version):
  return 'cu' + version.replace('.', '')

CUDA_version = torch.version.cuda
CUDA = format_cuda_version(CUDA_version)

!pip install torch-scatter -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-cluster -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-spline-conv -f https://data.pyg.org/whl/torch-{TORCH}+{CUDA}.html
!pip install torch-geometric

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.11.0+cu113.html
     |████████████████████████████████| 7.9 MB 24.6 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.11.0+cu113.html
     |████████████████████████████████| 3.5 MB 31.6 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.11.0+cu113.html
     |████████████████████████████████| 2.5 MB 16.8 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.11.0+cu113.html
     |████████████████████████████████| 750 kB 16.2 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     

# **Import Dependencies & Mount Gdrive**

In [2]:
import torch, os
from torch_geometric.datasets import Planetoid

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# **Data Paths, Paramaters & variables**

In [14]:
working_dir = '/content/drive/My Drive/Colab Notebooks/machine-learning-with-graphs/'

data_folder = 'Planetoid'
data_dir = os.path.join(working_dir, data_folder)

# **Load Dataset**

In [15]:
dataset = Planetoid(
                  root=data_dir, 
                  name='Cora'
                  )

*dataset* *properties*

In [16]:
print(dataset)
print("number of graphs           : ",len(dataset))
print("number of classes          : ",dataset.num_classes)
print("number of node features    : ",dataset.num_node_features)
print("number of edge features    : ",dataset.num_edge_features)

Cora()
number of graphs           :  1
number of classes          :  7
number of node features    :  1433
number of edge features    :  0


Dataset *shapes*

In [17]:
print(dataset.data)

'''
|V| = N = 2708
Embedding Dim (D) = 2708

'''

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])


'\n|V| = N = 2708\nEmbedding Dim (D) = 2708\n\n'

In [18]:
print("edge_index : ",dataset.data.edge_index.shape)
print(dataset.data.edge_index)

edge_index :  torch.Size([2, 10556])
tensor([[   0,    0,    0,  ..., 2707, 2707, 2707],
        [ 633, 1862, 2582,  ...,  598, 1473, 2706]])


In [19]:
print("train_mask : ",dataset.data.train_mask.shape)
print(dataset.data.train_mask)


train_mask :  torch.Size([2708])
tensor([ True,  True,  True,  ..., False, False, False])


In [20]:
print("x : ",dataset.data.x.shape)
print(dataset.data.x)


x :  torch.Size([2708, 1433])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [21]:
print("y : ",dataset.data.y.shape)
print(dataset.data.y)

y :  torch.Size([2708])
tensor([3, 4, 4,  ..., 3, 3, 3])


In [22]:
print(f"Train Size : {dataset.data.train_mask.sum()}")
print(f"Test  Size : {dataset.data.test_mask.sum()}")
print(f"valid Size : {dataset.data.val_mask.sum()}")

Train Size : 140
Test  Size : 1000
valid Size : 500


In [24]:
torch.sum(dataset.data.train_mask)

tensor(140)